const KEY='dreamfit-premium-v1';
const defaults={weights:[],meals:{breakfast:[],lunch:[],snack:[],dinner:[]},water:0,steps:0,extras:{calories:0,protein:0},completedExercises:{},customExercises:[]};
let state=load();
const mealMeta={breakfast:['Petit-déjeuner','🥣'],lunch:['Déjeuner','🍲'],snack:['Collation','🥛'],dinner:['Dîner','🥗']};
const programs={0:['WALK','Marche · gainage','push.webp',[]],1:['PUSH','Pectoraux · épaules · triceps','push.webp',['Développé couché','Développé incliné','Écarté poulie']],2:['PULL','Dos · biceps · arrière épaules','pull.webp',['Tirage vertical','Rowing poulie','Curl biceps']],3:['LEGS','Quadriceps · ischios · fessiers · mollets','legs.webp',['Presse à cuisses','Leg curl','Fentes']],4:['CARDIO','Endurance · récupération','legs.webp',['Cardio 30 minutes']],5:['PUSH','Pectoraux · épaules · triceps','push.webp',['Développé couché','Développé incliné','Élévations latérales']],6:['BACK & ARMS','Dos · biceps · triceps','pull.webp',['Rowing','Curl biceps','Extension triceps']]};
function load(){try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(defaults)}}function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function totals(){let t={calories:state.extras.calories||0,protein:state.extras.protein||0,carbs:0,fat:0};Object.values(state.meals).flat().forEach(x=>{t.calories+=+x.calories||0;t.protein+=+x.protein||0;t.carbs+=+x.carbs||0;t.fat+=+x.fat||0});return t}
function currentWeight(){return state.weights.length?state.weights[state.weights.length-1].value:null}
function score(){const t=totals(),w=currentWeight();let s=0;s+=Math.min(25,t.calories/2400*25);s+=Math.min(25,t.protein/200*25);s+=Math.min(20,state.water/4*20);s+=Math.min(20,state.steps/10000*20);if(w)s+=10;return Math.round(s)}
function render(){const t=totals(),sc=score(),w=currentWeight();$('#scoreValue').textContent=sc;$('#scoreRing').style.setProperty('--p',`${sc*3.6}deg`);$('#calories').textContent=Math.round(t.calories);$('#protein').textContent=`${Math.round(t.protein)} g`;$('#water').textContent=`${state.water.toFixed(1).replace('.',',')} L`;$('#steps').textContent=state.steps.toLocaleString('fr-FR');$('#nutCalories').textContent=Math.round(t.calories);$('#nutProtein').textContent=`${Math.round(t.protein)} g`;$('#nutCarbs').textContent=`${Math.round(t.carbs)} g`;$('#nutFat').textContent=`${Math.round(t.fat)} g`;$('#calProgress').style.width=`${Math.min(100,t.calories/2400*100)}%`;if(w){$('#currentWeight').textContent=`${w.toFixed(1).replace('.',',')} kg`;let pct=Math.max(0,Math.min(100,(104-w)/(104-92)*100));$('#weightProgress').style.width=`${pct}%`;$('#weightMessage').textContent=`${Math.max(0,w-92).toFixed(1).replace('.',',')} kg restants`;$('#chartWeight').textContent=`${w.toFixed(1).replace('.',',')} kg`;$('#goalPercent').textContent=`${Math.round(pct)} %`;$('#goalProgress').style.width=`${pct}%`;$('#goalRemaining').textContent=`${Math.max(0,w-92).toFixed(1).replace('.',',')} kg restants`;}else{$('#currentWeight').textContent='—';$('#weightProgress').style.width='0';$('#chartWeight').textContent='—';$('#goalPercent').textContent='0 %';$('#goalProgress').style.width='0';}
renderMeals();renderWorkout();drawChart()}
function renderMeals(){const box=$('#mealList');box.innerHTML='';for(const [key,[name,icon]] of Object.entries(mealMeta)){const arr=state.meals[key]||[],c=arr.reduce((a,b)=>a+(+b.calories||0),0),desc=arr.length?arr.map(x=>x.name).join(', '):'Aucun aliment renseigné';box.insertAdjacentHTML('beforeend',`<article class="meal"><div class="meal-icon">${icon}</div><div class="copy"><h4>${name}</h4><p><b>${Math.round(c)} kcal</b><br>${desc}</p></div><button data-action="meal" data-meal="${key}">+</button></article>`)} }
function renderWorkout(){const p=programs[new Date().getDay()];$('#workoutName').textContent=p[0];$('#workoutMuscles').textContent=p[1];$('#workoutImage').src=`assets/${p[2]}`;const list=[...p[3],...state.customExercises];$('#exerciseList').innerHTML=list.length?'':'<div class="goal-card"><p>Aucun exercice programmé aujourd’hui.</p></div>';list.forEach((name,i)=>{$('#exerciseList').insertAdjacentHTML('beforeend',`<article class="exercise"><div class="exercise-head"><h4>${name}</h4><span>${state.completedExercises[name]?'Terminé':'À faire'}</span></div><div class="fields"><label>KG<input inputmode="decimal" data-field="kg" data-name="${name}"></label><label>REPS<input inputmode="numeric" data-field="reps" data-name="${name}"></label><label>SÉRIES<input inputmode="numeric" data-field="sets" data-name="${name}" value="3"></label></div><button class="primary" data-action="complete" data-name="${name}">${state.completedExercises[name]?'✓ Exercice validé':'Valider l’exercice'}</button></article>`)} )}
function drawChart(){const c=$('#weightChart'),ctx=c.getContext('2d'),dpr=devicePixelRatio||1,w=c.clientWidth||350,h=220;c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);ctx.strokeStyle='#273144';ctx.lineWidth=1;for(let y=20;y<h;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}if(state.weights.length<2){ctx.fillStyle='#929bad';ctx.font='15px sans-serif';ctx.fillText('Ajoute plusieurs pesées pour afficher la courbe',16,h/2);return}const vals=state.weights.map(x=>x.value),min=Math.min(...vals)-1,max=Math.max(...vals)+1;ctx.beginPath();vals.forEach((v,i)=>{const x=i/(vals.length-1)*(w-24)+12,y=18+(max-v)/(max-min)*(h-42);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle='#9b55ff';ctx.lineWidth=4;ctx.stroke();vals.forEach((v,i)=>{const x=i/(vals.length-1)*(w-24)+12,y=18+(max-v)/(max-min)*(h-42);ctx.fillStyle='#d5b9ff';ctx.beginPath();ctx.arc(x,y,5,0,Math.PI*2);ctx.fill()})}
function nav(name){$$('.screen').forEach(x=>x.classList.toggle('active',x.dataset.screen===name));$$('.bottom button').forEach(x=>x.classList.toggle('active',x.dataset.nav===name));scrollTo(0,0)}
function modal(title,html){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;$('#modal').classList.add('open')}
function close(){ $('#modal').classList.remove('open') }
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1600)}
function form(fields,submit,label='Enregistrer'){return `<form class="form" data-submit="${submit}">${fields}<button class="primary">${label}</button></form>`}
document.addEventListener('click',e=>{const b=e.target.closest('[data-nav],[data-action]');if(!b)return;if(b.dataset.nav)return nav(b.dataset.nav);const a=b.dataset.action;if(a==='close')close();if(a==='add-weight')modal('Ajouter mon poids',form('<input name="value" type="number" step="0.1" placeholder="Poids en kg" required>','weight'));if(a==='add-water')modal('Ajouter de l’eau',form('<input name="value" type="number" step="0.1" placeholder="Quantité en litres" required>','water'));if(a==='add-steps')modal('Ajouter des pas',form('<input name="value" type="number" placeholder="Nombre de pas" required>','steps'));if(a==='add-calories')modal('Ajouter des calories',form('<input name="value" type="number" placeholder="Calories" required>','calories'));if(a==='add-protein')modal('Ajouter des protéines',form('<input name="value" type="number" placeholder="Grammes" required>','protein'));if(a==='meal'||a==='add-meal'){const key=b.dataset.meal||'breakfast';modal('Ajouter un aliment',form(`<select name="meal">${Object.entries(mealMeta).map(([k,v])=>`<option value="${k}" ${k===key?'selected':''}>${v[0]}</option>`).join('')}</select><input name="name" placeholder="Nom de l’aliment" required><input name="calories" type="number" placeholder="Calories" required><input name="protein" type="number" placeholder="Protéines (g)"><input name="carbs" type="number" placeholder="Glucides (g)"><input name="fat" type="number" placeholder="Lipides (g)">`,'meal'));}if(a==='add-exercise')modal('Ajouter un exercice',form('<input name="name" placeholder="Nom de l’exercice" required>','exercise'));if(a==='complete'){state.completedExercises[b.dataset.name]=!state.completedExercises[b.dataset.name];save();toast('Exercice mis à jour')}if(a==='start-workout')toast('Séance démarrée');if(a==='export'){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),x=document.createElement('a');x.href=url;x.download='dreamfit-donnees.json';x.click();URL.revokeObjectURL(url)}if(a==='import')$('#importInput').click();if(a==='reset'&&confirm('Supprimer toutes les données ?')){localStorage.removeItem(KEY);state=structuredClone(defaults);save()}if(a==='profile')modal('Objectifs',form('<input name="cal" value="2400" disabled><input name="prot" value="200" disabled><input name="water" value="4" disabled><input name="steps" value="10000" disabled>','noop','Fermer'));if(a==='weekly')modal('Bilan hebdomadaire','<p>Le bilan se construira automatiquement à partir de tes données réelles.</p>')});
document.addEventListener('submit',e=>{const f=e.target.closest('form');if(!f)return;e.preventDefault();const d=Object.fromEntries(new FormData(f));switch(f.dataset.submit){case'weight':state.weights.push({date:new Date().toISOString(),value:+d.value});break;case'water':state.water+=+d.value;break;case'steps':state.steps+=+d.value;break;case'calories':state.extras.calories+=+d.value;break;case'protein':state.extras.protein+=+d.value;break;case'meal':state.meals[d.meal].push({name:d.name,calories:+d.calories||0,protein:+d.protein||0,carbs:+d.carbs||0,fat:+d.fat||0});break;case'exercise':state.customExercises.push(d.name);break;case'noop':close();return}save();close();toast('Enregistré')});
$('#importInput').addEventListener('change',async e=>{try{state={...defaults,...JSON.parse(await e.target.files[0].text())};save();toast('Données importées')}catch{alert('Fichier invalide')}});$('#date').textContent=new Intl.DateTimeFormat('fr-FR',{weekday:'long',day:'numeric',month:'long'}).format(new Date());if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');render();
