'use strict';
const STORAGE_KEY='dreamfit_ai_clean_v2';
const DEFAULTS={
 profile:{name:'Anthony',weight:null,startWeight:null,targetWeight:92},
 goals:{calories:2400,protein:200,water:4,steps:10000,sleep:8},
 today:{calories:0,protein:0,carbs:0,fat:0,water:0,steps:0,sleep:0,score:0},
 meals:[
  {id:'breakfast',name:'Petit-déjeuner',kcal:0,desc:'Aucun aliment renseigné',done:false},
  {id:'lunch',name:'Déjeuner',kcal:0,desc:'Aucun aliment renseigné',done:false},
  {id:'snack',name:'Collation',kcal:0,desc:'Aucun aliment renseigné',done:false},
  {id:'dinner',name:'Dîner',kcal:0,desc:'Aucun aliment renseigné',done:false}
 ],
 schedule:{0:{type:'WALK',subtitle:'Marche · gainage',muscle:'push'},1:{type:'PUSH',subtitle:'Pectoraux · épaules · triceps',muscle:'push'},2:{type:'PULL',subtitle:'Dos · biceps · arrière épaules',muscle:'pull'},3:{type:'LEGS',subtitle:'Quadriceps · ischios · fessiers · mollets',muscle:'legs'},4:{type:'CARDIO',subtitle:'Cardio · mobilité',muscle:'legs'},5:{type:'PUSH',subtitle:'Pectoraux · épaules · triceps',muscle:'push'},6:{type:'BACK + ARMS',subtitle:'Dos · biceps · triceps',muscle:'pull'}},
 exercises:{PUSH:[{name:'Développé couché',sets:3},{name:'Développé incliné',sets:3},{name:'Écarté poulie',sets:3}],PULL:[{name:'Tirage vertical',sets:4},{name:'Rowing poulie',sets:4},{name:'Curl incliné',sets:3}],LEGS:[{name:'Presse à cuisses',sets:4},{name:'Leg curl',sets:4},{name:'Fentes',sets:3}],CARDIO:[{name:'Cardio',sets:1}],WALK:[{name:'Marche',sets:1},{name:'Gainage',sets:3}],'BACK + ARMS':[{name:'Tirage vertical',sets:4},{name:'Rowing poulie',sets:4},{name:'Curl marteau',sets:3},{name:'Extension triceps',sets:3}]},
 workoutLog:{},workoutStarted:false,weights:[]
};
let state=load(),route='home';
function clone(x){return JSON.parse(JSON.stringify(x))}
function merge(base,extra){if(!extra)return base;Object.keys(extra).forEach(k=>{if(extra[k]&&typeof extra[k]==='object'&&!Array.isArray(extra[k])&&base[k]&&typeof base[k]==='object'&&!Array.isArray(base[k]))merge(base[k],extra[k]);else base[k]=extra[k]});return base}
function load(){try{return merge(clone(DEFAULTS),JSON.parse(localStorage.getItem(STORAGE_KEY)||'null'))}catch(e){return clone(DEFAULTS)}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function fmt(v,d=0){return Number(v||0).toLocaleString('fr-FR',{minimumFractionDigits:d,maximumFractionDigits:d})}
function todayWorkout(){return state.schedule[new Date().getDay()]||state.schedule[1]}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),1800)}
function openModal(html){document.getElementById('modalContent').innerHTML=html;document.getElementById('modal').showModal()}
function closeModal(){document.getElementById('modal').close()}
function setRoute(r){route=r;document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.route===r));render();scrollTo({top:0,behavior:'smooth'})}
function metric(icon,label,val,foot,cls=''){return `<div class="metric"><div class="metric-label">${icon} ${label}</div><div class="metric-value ${cls}">${val}</div><div class="metric-foot">${foot}</div></div>`}
function render(){document.getElementById('app').innerHTML=({home:homeView,nutrition:nutritionView,workout:workoutView,progress:progressView,more:moreView}[route]||homeView)();bind()}
function homeView(){const p=state.profile,t=state.today,g=state.goals,hasWeight=Number.isFinite(Number(p.weight))&&p.weight!==null;let pct=0;if(hasWeight&&p.startWeight&&p.targetWeight!==p.startWeight)pct=Math.max(0,Math.min(100,Math.round((p.startWeight-p.weight)/(p.startWeight-p.targetWeight)*100)));return `<section class="screen"><div class="score-wrap"><div class="score-ring" style="--score:${t.score}"><div class="score-center"><div class="score-value">${t.score}</div><small>/100</small><b>Score du jour</b></div></div></div>${hasWeight?`<div class="card progress-card"><div class="between"><div><div class="mini-label">Poids actuel</div><strong>${fmt(p.weight,1)} kg</strong></div><div style="text-align:right"><div class="mini-label">Objectif</div><strong>${fmt(p.targetWeight,1)} kg</strong></div></div><div class="progress-bar"><span style="width:${pct}%"></span></div></div>`:`<div class="card empty"><h3>Commence ton suivi</h3><p>Ajoute ta première pesée pour afficher ta progression.</p><button class="primary-btn" data-action="add-weight">Ajouter mon poids</button></div>`}<div class="metric-grid">${metric('🔥','Calories',fmt(t.calories),'/ '+fmt(g.calories)+' kcal','accent-orange')}${metric('🥦','Protéines',fmt(t.protein)+' g','/ '+fmt(g.protein)+' g','accent-green')}${metric('💧','Eau',fmt(t.water,1)+' L','/ '+fmt(g.water,1)+' L','accent-blue')}${metric('👟','Pas',fmt(t.steps),'/ '+fmt(g.steps),'accent-purple')}</div><button class="primary-btn" style="margin-top:16px" data-action="go-workout">▶ Voir la séance du jour</button></section>`}
function nutritionView(){const t=state.today,g=state.goals;return `<section class="screen"><h2 class="screen-title">Nutrition</h2><p class="screen-subtitle">Aujourd’hui</p><div class="card"><div class="between"><div><div class="mini-label">Résumé du jour</div><div class="metric-value">${fmt(t.calories)} <small style="font-size:14px;color:var(--muted)">/ ${fmt(g.calories)} kcal</small></div></div><button class="icon-btn" data-action="edit-day">✎</button></div><div class="progress-bar"><span style="width:${Math.min(100,t.calories/g.calories*100)||0}%"></span></div></div><div class="section-head"><h2>Mes repas</h2><button class="icon-btn" data-action="add-meal">+</button></div><div class="meal-list">${state.meals.map(m=>`<button class="meal-row" data-meal="${m.id}"><div class="meal-thumb"></div><div><h3>${m.name}</h3><p><strong>${fmt(m.kcal)} kcal</strong><br>${m.desc}</p></div><span class="check ${m.done?'done':''}">${m.done?'✓':'○'}</span></button>`).join('')}</div></section>`}
function workoutView(){const w=todayWorkout(),list=state.exercises[w.type]||[];return `<section class="screen"><h2 class="screen-title">Entraînement</h2><p class="screen-subtitle">Programme du jour</p><div class="card workout-visual"><div class="copy"><div class="mini-label">Aujourd’hui</div><div class="workout-type">${w.type}</div><p>${w.subtitle}</p></div><img src="assets/muscles/${w.muscle}.png" alt="Muscles ciblés : ${w.subtitle}" onerror="this.style.display='none'"><button class="primary-btn" data-action="start-workout">${state.workoutStarted?'✓ Séance en cours':'▶ Commencer la séance'}</button></div><div class="section-head"><h2>Exercices</h2><button class="icon-btn" data-action="add-exercise">+</button></div>${list.map((e,i)=>exerciseCard(e,i,w.type)).join('')}<button class="secondary-btn" data-action="finish-workout">Terminer la séance</button></section>`}
function exerciseCard(e,i,type){const key=`${type}-${i}`,l=state.workoutLog[key]||{};return `<article class="card exercise-card"><div class="exercise-head"><h3>${e.name}</h3><span class="status">${l.done?'Terminé':'À faire'}</span></div><div class="fields"><div class="field"><label>kg</label><input inputmode="decimal" data-log="weight" data-key="${key}" value="${l.weight||''}"></div><div class="field"><label>reps</label><input inputmode="numeric" data-log="reps" data-key="${key}" value="${l.reps||''}"></div><div class="field"><label>séries</label><input inputmode="numeric" data-log="sets" data-key="${key}" value="${l.sets||e.sets}"></div></div><button class="primary-btn" style="margin-top:16px" data-complete="${key}">${l.done?'✓ Exercice validé':'Valider l’exercice'}</button></article>`}
function progressView(){const p=state.profile;if(!state.weights.length)return `<section class="screen"><h2 class="screen-title">Progrès</h2><div class="card empty"><h3>Aucune pesée enregistrée</h3><p>La courbe apparaîtra après ta première saisie.</p><button class="primary-btn" data-action="add-weight">Ajouter une pesée</button></div></section>`;const vals=state.weights,min=Math.min(...vals)-2,max=Math.max(...vals)+2,pts=vals.map((v,i)=>`${20+(vals.length===1?150:i*300/(vals.length-1))},${205-(v-min)/(max-min)*170}`).join(' '),area=`20,205 ${pts} 320,205`;return `<section class="screen"><h2 class="screen-title">Progrès</h2><div class="segmented"><button class="active">Poids</button><button data-action="not-ready">Mensurations</button><button data-action="not-ready">Photos</button></div><div class="card"><div class="between"><div><div class="metric-value">${fmt(p.weight,1)} kg</div><div class="mini-label">Poids actuel</div></div><div style="text-align:right"><div class="mini-label">Objectif</div><strong>${fmt(p.targetWeight,1)} kg</strong></div></div><svg class="chart" viewBox="0 0 340 230"><defs><linearGradient id="areaGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#8b3dff" stop-opacity=".42"/><stop offset="1" stop-color="#8b3dff" stop-opacity="0"/></linearGradient></defs><g class="chart-grid">${[40,80,120,160,200].map(y=>`<line x1="20" y1="${y}" x2="320" y2="${y}"/>`).join('')}</g><polygon class="chart-area" points="${area}"/><polyline class="chart-line" points="${pts}"/>${vals.map((v,i)=>`<circle class="chart-dot" cx="${20+(vals.length===1?150:i*300/(vals.length-1))}" cy="${205-(v-min)/(max-min)*170}" r="4"/>`).join('')}</svg></div><button class="primary-btn" style="margin-top:14px" data-action="add-weight">Ajouter une pesée</button></section>`}
function moreView(){return `<section class="screen"><h2 class="screen-title">Plus</h2><p class="screen-subtitle">Réglages et données</p><div class="menu-list"><button class="menu-item" data-action="edit-profile"><span>Profil</span><span>›</span></button><button class="menu-item" data-action="edit-goals"><span>Objectifs</span><span>›</span></button><button class="menu-item" data-action="export"><span>Exporter mes données</span><span>›</span></button><button class="menu-item" data-action="import"><span>Importer mes données</span><span>›</span></button><button class="menu-item" style="color:var(--danger)" data-action="reset"><span>Réinitialiser les données</span><span>›</span></button></div></section>`}
function bind(){
 document.querySelectorAll('[data-action]').forEach(el=>el.addEventListener('click',()=>action(el.dataset.action)));
 document.querySelectorAll('[data-log]').forEach(input=>input.addEventListener('input',e=>{const k=e.target.dataset.key;state.workoutLog[k]=state.workoutLog[k]||{};state.workoutLog[k][e.target.dataset.log]=e.target.value;save()}));
 document.querySelectorAll('[data-complete]').forEach(btn=>btn.addEventListener('click',()=>{const k=btn.dataset.complete;state.workoutLog[k]=state.workoutLog[k]||{};state.workoutLog[k].done=!state.workoutLog[k].done;save();render()}));
 document.querySelectorAll('[data-meal]').forEach(btn=>btn.addEventListener('click',()=>editMeal(btn.dataset.meal)));
}
function action(a){if(a==='go-workout')return setRoute('workout');if(a==='add-weight')return weightModal();if(a==='add-meal')return mealModal();if(a==='edit-day')return dayModal();if(a==='add-exercise')return exerciseModal();if(a==='start-workout'){state.workoutStarted=true;save();toast('Séance commencée');return render()}if(a==='finish-workout'){state.workoutStarted=false;state.today.score=Math.min(100,state.today.score+10);save();toast('Séance enregistrée');return render()}if(a==='edit-profile')return profileModal();if(a==='edit-goals')return goalsModal();if(a==='export')return exportData();if(a==='import')return importData();if(a==='reset'){if(confirm('Effacer toutes les données enregistrées ?')){localStorage.removeItem(STORAGE_KEY);state=clone(DEFAULTS);render();toast('Données effacées')}return}if(a==='not-ready')return toast('Cette section arrive ensuite')}
function weightModal(){openModal(`<h2>Ajouter une pesée</h2><label>Poids (kg)</label><input id="w" type="number" step="0.1" value="${state.profile.weight||''}" placeholder="Ex. 98,2"><div class="modal-actions"><button class="secondary-btn">Annuler</button><button class="primary-btn" type="button" id="saveW">Enregistrer</button></div>`);document.getElementById('saveW').onclick=()=>{const v=parseFloat(document.getElementById('w').value);if(!Number.isFinite(v))return toast('Entre un poids valide');if(!state.profile.startWeight)state.profile.startWeight=v;state.profile.weight=v;state.weights.push(v);save();closeModal();render();toast('Poids enregistré')}}
function dayModal(){const t=state.today;openModal(`<h2>Données du jour</h2><label>Calories</label><input id="cal" type="number" value="${t.calories}"><label>Protéines (g)</label><input id="pro" type="number" value="${t.protein}"><label>Eau (L)</label><input id="wat" type="number" step="0.1" value="${t.water}"><label>Pas</label><input id="ste" type="number" value="${t.steps}"><div class="modal-actions"><button class="secondary-btn">Annuler</button><button class="primary-btn" type="button" id="saveDay">Enregistrer</button></div>`);document.getElementById('saveDay').onclick=()=>{t.calories=+document.getElementById('cal').value||0;t.protein=+document.getElementById('pro').value||0;t.water=+document.getElementById('wat').value||0;t.steps=+document.getElementById('ste').value||0;t.score=Math.min(100,Math.round((Math.min(1,t.protein/state.goals.protein)+Math.min(1,t.water/state.goals.water)+Math.min(1,t.steps/state.goals.steps)+Math.min(1,t.calories/state.goals.calories))*25));save();closeModal();render()}}
function editMeal(id){const m=state.meals.find(x=>x.id===id);openModal(`<h2>${m.name}</h2><label>Calories</label><input id="mk" type="number" value="${m.kcal||''}"><label>Aliments / description</label><textarea id="md" rows="4">${m.desc==='Aucun aliment renseigné'?'':m.desc}</textarea><label><input id="done" type="checkbox" ${m.done?'checked':''}> Repas terminé</label><div class="modal-actions"><button class="secondary-btn">Annuler</button><button class="primary-btn" type="button" id="saveM">Enregistrer</button></div>`);document.getElementById('saveM').onclick=()=>{m.kcal=+document.getElementById('mk').value||0;m.desc=document.getElementById('md').value.trim()||'Aucun aliment renseigné';m.done=document.getElementById('done').checked;state.today.calories=state.meals.reduce((s,x)=>s+(+x.kcal||0),0);save();closeModal();render()}}
function mealModal(){openModal(`<h2>Ajouter un repas</h2><label>Nom</label><input id="mn" placeholder="Ex. Après entraînement"><label>Calories</label><input id="mk" type="number"><label>Description</label><textarea id="md" rows="3"></textarea><div class="modal-actions"><button class="secondary-btn">Annuler</button><button class="primary-btn" type="button" id="saveM">Ajouter</button></div>`);document.getElementById('saveM').onclick=()=>{state.meals.push({id:'m'+Date.now(),name:document.getElementById('mn').value.trim()||'Repas',kcal:+document.getElementById('mk').value||0,desc:document.getElementById('md').value.trim()||'Aucun aliment renseigné',done:false});state.today.calories=state.meals.reduce((s,x)=>s+(+x.kcal||0),0);save();closeModal();render()}}
function exerciseModal(){const type=todayWorkout().type;openModal(`<h2>Ajouter un exercice</h2><label>Nom</label><input id="en" placeholder="Ex. Développé militaire"><label>Séries</label><input id="es" type="number" value="3"><div class="modal-actions"><button class="secondary-btn">Annuler</button><button class="primary-btn" type="button" id="saveE">Ajouter</button></div>`);document.getElementById('saveE').onclick=()=>{state.exercises[type]=state.exercises[type]||[];state.exercises[type].push({name:document.getElementById('en').value.trim()||'Nouvel exercice',sets:+document.getElementById('es').value||3});save();closeModal();render()}}
function profileModal(){openModal(`<h2>Profil</h2><label>Prénom</label><input id="pn" value="${state.profile.name}"><div class="modal-actions"><button class="secondary-btn">Annuler</button><button class="primary-btn" type="button" id="saveP">Enregistrer</button></div>`);document.getElementById('saveP').onclick=()=>{state.profile.name=document.getElementById('pn').value.trim()||'Anthony';document.getElementById('profileButton').textContent=state.profile.name.slice(0,2).toUpperCase();save();closeModal();render()}}
function goalsModal(){const g=state.goals,p=state.profile;openModal(`<h2>Objectifs</h2><label>Poids cible</label><input id="tw" type="number" step="0.1" value="${p.targetWeight}"><label>Calories</label><input id="gc" type="number" value="${g.calories}"><label>Protéines (g)</label><input id="gp" type="number" value="${g.protein}"><label>Eau (L)</label><input id="gw" type="number" step="0.1" value="${g.water}"><label>Pas</label><input id="gs" type="number" value="${g.steps}"><div class="modal-actions"><button class="secondary-btn">Annuler</button><button class="primary-btn" type="button" id="saveG">Enregistrer</button></div>`);document.getElementById('saveG').onclick=()=>{p.targetWeight=+document.getElementById('tw').value||92;g.calories=+document.getElementById('gc').value||2400;g.protein=+document.getElementById('gp').value||200;g.water=+document.getElementById('gw').value||4;g.steps=+document.getElementById('gs').value||10000;save();closeModal();render()}}
function exportData(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='dreamfit-donnees.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importData(){const i=document.createElement('input');i.type='file';i.accept='.json';i.onchange=()=>{if(!i.files[0])return;const r=new FileReader();r.onload=()=>{try{state=merge(clone(DEFAULTS),JSON.parse(r.result));save();render();toast('Données importées')}catch(e){toast('Fichier invalide')}};r.readAsText(i.files[0])};i.click()}
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>setRoute(b.dataset.route)));
document.getElementById('profileButton').addEventListener('click',profileModal);
document.getElementById('todayLabel').textContent=new Date().toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long'});
document.getElementById('profileButton').textContent=state.profile.name.slice(0,2).toUpperCase();
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
render();
