const KEY='dreamfit_studio_v1';
const defaults={water:0,steps:0,weights:[],foods:[],completedExercises:{},customExercises:[]};
let state=load();
const plans={
0:{name:'RÉCUP',muscles:'Marche · Gainage',image:'assets/push.png',exercises:['Marche 45 min','Gainage']},
1:{name:'PUSH',muscles:'Pectoraux · Épaules · Triceps',image:'assets/push.png',exercises:['Développé couché','Développé incliné','Écarté poulie','Développé épaules','Élévations latérales','Extension triceps']},
2:{name:'PULL',muscles:'Dos · Biceps · Arrière épaules',image:'assets/pull.png',exercises:['Tirage vertical','Rowing assis','Rowing haltère','Oiseau poulie','Curl incliné','Curl marteau']},
3:{name:'LEGS',muscles:'Quadriceps · Ischios · Fessiers · Mollets',image:'assets/legs.png',exercises:['Presse à cuisses','Leg curl','Fentes','Hip thrust','Mollets debout','Gainage']},
4:{name:'CARDIO',muscles:'Endurance · Mobilité',image:'assets/legs.png',exercises:['Cardio 30 min','Mobilité 15 min']},
5:{name:'PUSH',muscles:'Pectoraux · Épaules · Triceps',image:'assets/push.png',exercises:['Développé couché','Développé incliné','Écarté poulie','Développé épaules','Élévations latérales','Extension triceps']},
6:{name:'BACK & ARMS',muscles:'Dos · Biceps · Triceps',image:'assets/pull.png',exercises:['Tirage vertical','Rowing assis','Curl biceps','Curl marteau','Extension triceps','Dips assistés']}
};
function load(){try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function fmt(n,d=0){return Number(n||0).toLocaleString('fr-FR',{minimumFractionDigits:d,maximumFractionDigits:d})}
function today(){return new Date().toISOString().slice(0,10)}
function totals(){return state.foods.reduce((a,f)=>{a.kcal+=+f.kcal||0;a.p+=+f.p||0;a.c+=+f.c||0;a.f+=+f.f||0;return a},{kcal:0,p:0,c:0,f:0})}
function score(){const t=totals();let s=10;s+=Math.min(25,t.kcal/2400*25);s+=Math.min(20,t.p/200*20);s+=Math.min(15,state.water/4*15);s+=Math.min(15,state.steps/10000*15);if(state.weights.length)s+=5;if(Object.keys(state.completedExercises).some(k=>k.startsWith(today())))s+=10;return Math.round(Math.min(100,s))}
function showToast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function openSheet(id){document.getElementById(id).classList.add('open')}
function closeSheet(id){document.getElementById(id).classList.remove('open')}
function render(){
 const d=new Date();document.querySelector('#dateLabel').textContent=d.toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long'});
 const sc=score();document.querySelector('#scoreValue').textContent=sc;document.querySelector('#scoreRing').style.background=`conic-gradient(from 220deg,#26c7ef 0 ${sc*.55}%,#8c2cff ${sc*.55}% ${sc}%,#1f2634 ${sc}% 100%)`;
 const t=totals();document.querySelector('#homeCalories').textContent=fmt(t.kcal);document.querySelector('#homeProtein').textContent=fmt(t.p)+' g';document.querySelector('#homeWater').textContent=fmt(state.water,1)+' L';document.querySelector('#homeSteps').textContent=fmt(state.steps);
 ['nutritionCalories'].forEach(id=>document.getElementById(id).textContent=fmt(t.kcal));document.querySelector('#nutritionProtein').textContent=fmt(t.p)+' g';document.querySelector('#nutritionCarbs').textContent=fmt(t.c)+' g';document.querySelector('#nutritionFat').textContent=fmt(t.f)+' g';document.querySelector('#calProgress').style.width=Math.min(100,t.kcal/2400*100)+'%';
 renderWeight();renderMeals();renderWorkout();drawChart();
}
function renderWeight(){const ws=[...state.weights].sort((a,b)=>a.date.localeCompare(b.date));const empty=!ws.length;document.querySelector('#weightEmpty').classList.toggle('hidden',!empty);document.querySelector('#weightCard').classList.toggle('hidden',empty);if(empty){document.querySelector('#progressWeight').textContent='—';document.querySelector('#progressDelta').textContent='—';document.querySelector('#targetPct').textContent='0 %';document.querySelector('#remainingWeight').textContent='Ajoute une pesée pour commencer.';return}const first=ws[0].value,last=ws.at(-1).value,goal=92;const lost=first-last;const pct=Math.max(0,Math.min(100,lost/(first-goal)*100));document.querySelector('#currentWeight').textContent=fmt(last,1)+' kg';document.querySelector('#weightDelta').textContent=(lost>=0?'-':'+')+fmt(Math.abs(lost),1)+' kg depuis le départ';document.querySelector('#weightProgress').style.width=pct+'%';document.querySelector('#progressWeight').textContent=fmt(last,1)+' kg';document.querySelector('#progressDelta').textContent=(lost>=0?'-':'+')+fmt(Math.abs(lost),1)+' kg';document.querySelector('#targetPct').textContent=Math.round(pct)+' %';document.querySelector('#targetProgress').style.width=pct+'%';document.querySelector('#remainingWeight').textContent=last>goal?fmt(last-goal,1)+' kg restants':'Objectif atteint';}
function renderMeals(){const types=['Petit-déjeuner','Déjeuner','Collation','Dîner','Avant de dormir'];const box=document.querySelector('#mealList');box.innerHTML='';types.forEach((type,i)=>{const foods=state.foods.filter(f=>f.type===type);const kcal=foods.reduce((s,f)=>s+(+f.kcal||0),0);const el=document.createElement('button');el.className='meal-card card';el.innerHTML=`<div class='meal-thumb'>${['🥣','🍗','🥛','🥘','🌙'][i]}</div><div><h4>${type}</h4><p>${foods.length?foods.map(f=>`${f.name}${f.qty?` · ${f.qty} g`:''}`).join(' • '):'Aucun aliment renseigné'}</p>${foods.length?`<div class='food-lines'>${foods.slice(0,4).map(f=>`<span>${f.name}</span>`).join('')}</div>`:''}</div><div class='meal-total'>${fmt(kcal)} kcal</div>`;el.onclick=()=>{document.querySelector('#mealType').value=type;openSheet('mealSheet')};box.appendChild(el)});}
function renderWorkout(){const plan=plans[new Date().getDay()];document.querySelector('#workoutName').textContent=plan.name;document.querySelector('#workoutMuscles').textContent=plan.muscles;document.querySelector('#workoutImage').src=plan.image;const list=document.querySelector('#exerciseList');list.innerHTML='';[...plan.exercises,...state.customExercises].forEach((name,i)=>{const key=`${today()}_${name}`;const done=!!state.completedExercises[key];const card=document.createElement('div');card.className='exercise-card card'+(done?' completed':'');card.innerHTML=`<div class='exercise-head'><h4>${name}</h4><span class='status'>${done?'Terminé':'À faire'}</span></div><div class='exercise-fields'><label>KG<input inputmode='decimal' data-field='kg' value='${state.completedExercises[key]?.kg||''}'></label><label>REPS<input inputmode='numeric' data-field='reps' value='${state.completedExercises[key]?.reps||''}'></label><label>SÉRIES<input inputmode='numeric' data-field='sets' value='${state.completedExercises[key]?.sets||3}'></label></div><button class='secondary'>${done?'✓ Exercice validé':'Valider l’exercice'}</button>`;card.querySelector('button').onclick=()=>{const inputs=card.querySelectorAll('input');state.completedExercises[key]={kg:inputs[0].value,reps:inputs[1].value,sets:inputs[2].value};save();showToast('Exercice enregistré')};list.appendChild(card)});}
function drawChart(){const c=document.querySelector('#weightChart'),ctx=c.getContext('2d'),ws=[...state.weights].sort((a,b)=>a.date.localeCompare(b.date));ctx.clearRect(0,0,c.width,c.height);ctx.strokeStyle='#232b38';ctx.lineWidth=1;for(let i=0;i<5;i++){const y=30+i*75;ctx.beginPath();ctx.moveTo(20,y);ctx.lineTo(c.width-20,y);ctx.stroke()}if(ws.length<2){ctx.fillStyle='#8d97aa';ctx.font='28px -apple-system';ctx.textAlign='center';ctx.fillText('Ajoute au moins deux pesées',c.width/2,c.height/2);return}const vals=ws.map(w=>+w.value),min=Math.min(...vals)-1,max=Math.max(...vals)+1;const pts=vals.map((v,i)=>({x:30+i*(c.width-60)/(vals.length-1),y:30+(max-v)/(max-min)*(c.height-70)}));const grad=ctx.createLinearGradient(0,0,c.width,0);grad.addColorStop(0,'#9d46ff');grad.addColorStop(1,'#2dc8f0');ctx.strokeStyle=grad;ctx.lineWidth=6;ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.fillStyle='#b766ff';pts.forEach(p=>{ctx.beginPath();ctx.arc(p.x,p.y,8,0,Math.PI*2);ctx.fill()});}

document.addEventListener('click',e=>{const nav=e.target.closest('[data-nav]');if(nav){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===nav.dataset.nav));document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===nav.dataset.nav));scrollTo({top:0,behavior:'smooth'});render()}const a=e.target.closest('[data-action]');if(a){const x=a.dataset.action;if(x==='open-meal')openSheet('mealSheet');if(x==='open-weight')openSheet('weightSheet');if(x==='water'){state.water=Math.min(4,state.water+.25);save()}if(x==='steps')openSheet('stepsSheet');if(x==='add-exercise'){const n=prompt('Nom de l’exercice');if(n){state.customExercises.push(n);save()}}if(x==='export'){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const u=URL.createObjectURL(blob);const l=document.createElement('a');l.href=u;l.download='dreamfit-donnees.json';l.click();URL.revokeObjectURL(u)}if(x==='reset'&&confirm('Supprimer toutes les données ?')){state=structuredClone(defaults);save();showToast('Données supprimées')}}const cl=e.target.closest('[data-close]');if(cl)closeSheet(cl.dataset.close)});
document.querySelector('#saveFood').onclick=()=>{const f={type:mealType.value,name:foodName.value.trim(),qty:+foodQty.value||0,kcal:+foodKcal.value||0,p:+foodProtein.value||0,c:+foodCarbs.value||0,f:+foodFat.value||0,date:today()};if(!f.name)return showToast('Indique le nom de l’aliment');state.foods.push(f);['foodName','foodQty','foodKcal','foodProtein','foodCarbs','foodFat'].forEach(id=>document.getElementById(id).value='');closeSheet('mealSheet');save();showToast('Aliment ajouté')};
document.querySelector('#saveWeight').onclick=()=>{const value=+String(weightInput.value).replace(',','.');if(!value)return showToast('Indique ton poids');state.weights.push({value,date:weightDate.value||today()});closeSheet('weightSheet');save();showToast('Pesée enregistrée')};
document.querySelector('#saveSteps').onclick=()=>{state.steps=+stepsInput.value||0;closeSheet('stepsSheet');save();showToast('Pas enregistrés')};
document.querySelector('#weightDate').value=today();
document.querySelector('#startWorkout').onclick=()=>{document.querySelector('#exerciseList').scrollIntoView({behavior:'smooth'});showToast('Séance démarrée')};
document.querySelector('#importFile').onchange=e=>{const r=new FileReader();r.onload=()=>{try{state={...defaults,...JSON.parse(r.result)};save();showToast('Données importées')}catch{showToast('Fichier invalide')}};r.readAsText(e.target.files[0])};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');render();
